#ifndef __MainExecutablePanelMain__
#define __MainExecutablePanelMain__

/**
@file
Subclass of PanelMain, which is generated by wxFormBuilder.
*/
//#include <wx/timer.h>

#include <PlayerTime.h>
#include <boost/filesystem/path.hpp>
#include "MainExecutable.h"



//// end generated include

/** Implementing PanelMain */
class MainExecutablePanelMain : public PanelMain
{
	protected:
        void btnStopClick( wxCommandEvent& event );
		void toggleBtnPlayPauseClick( wxCommandEvent& event );
        void btnExitClick( wxCommandEvent& event );
	public:
		/** Constructor */
		MainExecutablePanelMain( wxWindow* parent );
	//// end generated class members

    void set_percentage(double value);
    void set_time_label(wxString timeLabel);
    void timer_tick();

private:
	boost::filesystem::path video_files_path;
    PlayerTime time;
    PlayerTime totaltime;
    bool timer_enabled = false;
    bool time_zero();
    void open_video() const;
    void pause_video() const;
};



#endif // __MainExecutablePanelMain__
