#ifndef __FormMainPanelMain__
#define __FormMainPanelMain__

/**
@file
Subclass of PanelMain, which is generated by wxFormBuilder.
*/

#include "FormMain.h"

//// end generated include

/** Implementing PanelMain */
class FormMainPanelMain : public PanelMain
{
	protected:
		// Handlers for PanelMain events.
		void btnSearchVideoDirClicked( wxCommandEvent& event );
		void btnSaveAndExit( wxCommandEvent& event );
	public:
		/** Constructor */
		FormMainPanelMain( FormMainDerived* parent );
	//// end generated class members
	
};

#endif // __FormMainPanelMain__
